language: python
python:
  - "3.6"
script:
  - make test
install:
  - pip install -r requirements.txt
env:
  - SKETAL_GROUP_IGNORE=0 SKETAL_USER_IGNORE=1
  - SKETAL_GROUP_IGNORE=1 SKETAL_USER_IGNORE=0
  - SKETAL_GROUP_IGNORE=0 SKETAL_USER_IGNORE=0
